baseurl = "https://blog.hugozhu.site"
DefaultContentLanguage = "en"
title = "All about Raspberry Pi"
# Using theme as git submodule 
theme = "beautifulhugo"
# Or when using theme as hugo module
# theme = "github.com/halogenica/beautifulhugo"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
disqusShortname = "hugozhu"
googleAnalytics = "GTM-W88HDMN"
enableRobotsTXT = true

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Params]
  homeTitle = "Hugo Zhu's Blog"
  tableOfContents = true
  subtitle = ""
  mainSections = ["post", "posts"]
  logo = "img/pi.png" # Expecting square dimensions
  favicon = "img/pi.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  hideAuthor = true
  gcse = "617d351a633194d48" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "Hugo Zhu"
  website = "blog.hugozhu.site"
  email = "hugozhu@gmail.com"
  facebook = "hugozhu"
  github = "hugozhu"
  #gitlab = "username"
  #bitbucket = "username"
  #twitter = "hugozhu"
  #reddit = "username"
  linkedin = "hugozhu"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  weibo = "hugozhu"
  #slack = "username"
  #medium = "username"
  #discord = "invite code (https://discord.gg/XXXXXXX)"
  #strava = "userid"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    identifier = "tools"
    name = "Tools"
    weight = 2

[[menu.main]]
    parent = "tools"
    name = "HTML Tools"
    url = "https://nddapp.com/json-encoder.html"
    weight = 1

[[menu.main]]
    parent = "tools"
    name = "Imaeg Resizing"
    url = "https://www.birme.net/"
    weight = 2

[[menu.main]]
    parent = "tools"
    name = "JWT Token Tool"
    url = "https://jwt.io/"
    weight = 3

#[[menu.main]]
#    parent = "samples"
#    name = "Math Sample"
#    url = "post/2017-03-05-math-sample"
#    weight = 2

#[[menu.main]]
#    parent = "samples"
#    name = "Code Sample"
#    url = "post/2016-03-08-code-sample"
#    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
